apiVersion: apps/v1
kind: Deployment
metadata:
  name: podrhama-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: podrhama
  template:
    metadata:
      labels:
        app: podrhama
    spec:
      containers:
      - name: podrhama
        image: rhamanalysis/rhama-hidro-authenticator-app:production-10096
        env:
        - name: KC_DB_URL
          valueFrom:
            secretKeyRef:
              name: keyclock-database-secret
              key: KC_DB_URL
        volumeMounts:
        - name: config-volume
          mountPath: /etc/nginx/nginx.conf
          subPath: nginx.conf
        resources:
          limits:
            memory: "300Mi"
            cpu: "1.0"
          requests:
            memory: "150Mi"
            cpu: "0.5"
      volumes:
      - name: config-volume
        configMap:
          name: nginx-config
      imagePullSecrets:
      - name: docker-hub-secret

---
apiVersion: v1
kind: Service
metadata:
  name: podrhama-service
spec:
  type: ClusterIP
  selector:
    app: podrhama
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
