apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: login.vexus.solutions
  namespace: vexus
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - login.vexus.solutions
    secretName: vexus.solutions
  rules:
  - host: login.vexus.solutions
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: vexus-keycloak-service-main
            port:
              number: 4500
