apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
    pv.kubernetes.io/provisioned-by: blob.csi.azure.com
  name: keycloak-storage-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
  - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain # If set as "Delete" container would be removed after pvc deletion
  storageClassName: "azureblob-fuse-premium-rhap1zu2sta002"
  mountOptions:
  - -o allow_other
  - --file-cache-timeout-in-seconds=120
  csi:
    driver: blob.csi.azure.com
    # volumeid has to be unique for every identical storage blob container in the cluster
    # character `#`and `/` are reserved for internal use and cannot be used in volumehandle
    volumeHandle: 77fd14a5-d328-4569-871a-af88d6d4dcb6
    volumeAttributes:
      containerName: default
    nodeStageSecretRef:
      name: storage-keycloak-secret
      namespace: vexus
