apiVersion: v1
kind: Secret
metadata:
  name: keycloak-database-secret
type: Opaque
data:
  KC_HOSTNAME: bG9naW4udmV4dXMuc29sdXRpb25z
  KC_DB: a2V5Y2xvYWs=
  KC_DB_URL: cmhhcDF6dTJhcHMwMDEucG9zdGdyZXMuZGF0YWJhc2UuYXp1cmUuY29tOjU0MzI=
  KC_DB_USERNAME: a2V5Y2xvYWs=
  KC_DB_PASSWORD: U0c0ZFElVEpMU0pdTDFuKQ==
  KC_DB_SCHEMA: cHVibGlj
  KEYCLOAK_ADMIN: a2V5Y2xvYWs=
  KEYCLOAK_ADMIN_PASSWORD: a2V5Y2xvYWs=
  KC_LOG_LEVEL: REVCVUc=
