apiVersion: apps/v1
kind: Deployment
metadata:
  name: blogapp
spec:
  selector:
    matchLabels:
      app: blogapp
  template:
    metadata:
      labels:
        app: blogapp
    spec:
      containers:
      - name: blogapp
        image: viniciuspoa2/app-php
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
          requests:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
      - name: nginx-loadbalancer-container
        image: nginx
        resources:
          limits:
            memory: "300Mi"
            cpu: "1.0"
          requests:
            memory: "150Mi"
            cpu: "0.5"

---
apiVersion: v1
kind: Service
metadata:
  name: blogapp-service
spec:
  selector:
    app: blogapp
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
