apiVersion: v1
kind: Pod
metadata:
  name: double-pod-nginx
spec:
  containers:
  - name: nginx-loadbalancer1
    image: nginx
    resources:
      limits:
        memory: "200Mi"
        cpu: "0.5"
      requests:
        memory: "100Mi"
        cpu: "0.2"
  - name: nginx-loadbalancer2
    image: nginx
    resources:
      limits:
        memory: "300Mi"
        cpu: "1.0"
      requests:
        memory: "150Mi"
        cpu: "0.5"
