apiVersion: apps/v1
kind: Deployment
metadata:
  name: blogapp
spec:
  selector:
    matchLabels:
      app: blogapp
  template:
    metadata:
      labels:
        app: blogapp
    spec:
      containers:
      - name: blogapp
        image: viniciuspoa2/app-php
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
          requests:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
